const appts = [
  {
    horario: "2024-05-10T22:46:00.000Z",
    ocupado: true,
    doctor_id: "1",
    patient_name: "Carlos Silva",
    plano_saude: "UNIMED",
    tipo_exame: "us",
    nome_exame: "Abdomen",
  },
  {
    horario: "2024-05-10T23:16:00.000Z",
    ocupado: false,
    doctor_id: "1",
    patient_name: null,
    plano_saude: null,
    tipo_exame: "us",
    nome_exame: "Tireóide",
  },
  {
    horario: "2024-05-10T23:46:00.000Z",
    ocupado: true,
    doctor_id: "1",
    patient_name: "Ana Paula",
    plano_saude: "CASSI",
    tipo_exame: "TC",
    nome_exame: "Coronária",
  },
  {
    horario: "2024-05-11T00:16:00.000Z",
    ocupado: true,
    doctor_id: "1",
    patient_name: "Marcos Almeida",
    plano_saude: "Bradesco",
    tipo_exame: "TC",
    nome_exame: "Coronária",
  },
  {
    horario: "2024-05-11T00:46:00.000Z",
    ocupado: true,
    doctor_id: "2",
    patient_name: "Luciana Ferreira",
    plano_saude: "CAIXA",
    tipo_exame: "ECO",
    nome_exame: "Trastorácio",
  },
  {
    horario: "2024-05-11T01:16:00.000Z",
    ocupado: true,
    doctor_id: "2",
    patient_name: "Marcos Almeida",
    plano_saude: "Bradesco",
    tipo_exame: "tc",
    nome_exame: "Coronária",
  },
  {
    horario: "2024-05-11T01:46:00.000Z",
    ocupado: true,
    doctor_id: "2",
    patient_name: "Luciana Ferreira",
    plano_saude: "CAIXA",
    tipo_exame: "ECO",
    nome_exame: "Com estresse",
  },
  {
    horario: "2024-05-11T02:16:00.000Z",
    ocupado: true,
    doctor_id: "2",
    patient_name: "Fernanda Santos",
    plano_saude: "IPASGO",
    tipo_exame: "us",
    nome_exame: "Tireóide",
  },
  {
    horario: "2024-05-11T02:46:00.000Z",
    ocupado: true,
    doctor_id: "3",
    patient_name: "João Pereira",
    plano_saude: "UNIMED",
    tipo_exame: "ECO",
    nome_exame: "Transesofágico",
  },
  {
    horario: "2024-05-11T03:16:00.000Z",
    ocupado: true,
    doctor_id: "3",
    patient_name: "Carlos Silva",
    plano_saude: "secretaria",
    tipo_exame: "us",
    nome_exame: "US Abdomen",
  },
  {
    horario: "2024-05-11T03:46:00.000Z",
    ocupado: true,
    doctor_id: "3",
    patient_name: "Ana Paula",
    plano_saude: "CASSI",
    tipo_exame: "TC",
    nome_exame: "Coronária",
  },
  {
    horario: "2024-05-11T04:16:00.000Z",
    ocupado: true,
    doctor_id: "3",
    patient_name: "Fernanda Santos",
    plano_saude: "PARTICULAR",
    tipo_exame: "us",
    nome_exame: "Abdomen",
  },
];

export default appts;
